version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/company.db
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - api
